# Site settings
title: Marcus Almeida
description: "Software's Craftsman"
url: 'http://marcusalmeida.github.io/' 
baseurl: '/'
google_analytics: 'UA-72489345-1'
author:
  name: 'Marcus Almeida'
  email: marcusmage@gmail.com
  twitter_username: marcusalmeida
  github_username:  marcusalmeida

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
  highlighter: rouge

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']